version: "3.9"

services:
  neo4j:
    image: neo4j:5.26.0
    container_name: neo4j-graphrag
    restart: unless-stopped
    environment:
      NEO4J_AUTH: "${NEO4J_USERNAME:-neo4j}/${NEO4J_PASSWORD:-neo4j}"
      NEO4J_server_default__listen__address: 0.0.0.0
      NEO4J_server_bolt_advertised__address: "${NEO4J_BOLT_ADVERTISED_ADDRESS:-localhost:7687}"
      NEO4J_server_http_advertised__address: "${NEO4J_HTTP_ADVERTISED_ADDRESS:-localhost:7474}"
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
      NEO4JLABS_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - type: bind
        source: ./.data/neo4j/data
        target: /data
      - type: bind
        source: ./.data/neo4j/logs
        target: /logs
      - type: bind
        source: ./.data/neo4j/import
        target: /import
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -a bolt://127.0.0.1:7687 -u ${NEO4J_USERNAME:-neo4j} -p ${NEO4J_PASSWORD:-neo4j} 'RETURN 1;' >/dev/null 2>&1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  qdrant:
    image: qdrant/qdrant:1.9.4
    container_name: qdrant-graphrag
    restart: unless-stopped
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__CLUSTER__ENABLED: "false"
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - type: bind
        source: ./.data/qdrant/storage
        target: /qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:6333/readyz"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

networks:
  default:
    name: graphrag-local
