services:
  neo4j:
    image: neo4j:5.26.12
    container_name: neo4j-graphrag
    restart: unless-stopped
    environment:
      NEO4J_AUTH: "${NEO4J_USERNAME:-neo4j}/${NEO4J_PASSWORD:-neo4j}"
      NEO4J_server_default__listen__address: 0.0.0.0
      NEO4J_server_bolt_advertised__address: "${NEO4J_BOLT_ADVERTISED_ADDRESS:-neo4j:7687}"
      NEO4J_server_http_advertised__address: "${NEO4J_HTTP_ADVERTISED_ADDRESS:-neo4j:7474}"
      NEO4J_dbms_security_procedures_allowlist: apoc.*
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "${NEO4J_ACCEPT_LICENSE_AGREEMENT:-yes}"
      NEO4J_server_memory_heap__initial__size: "${NEO4J_HEAP_INITIAL_SIZE:-256m}"
      NEO4J_server_memory_heap__max__size: "${NEO4J_HEAP_MAX_SIZE:-512m}"
    ports:
      - "${NEO4J_HTTP_PORT:-7474}:7474"
      - "${NEO4J_BOLT_PORT:-7687}:7687"
    volumes:
      - type: bind
        source: ./.data/neo4j/data
        target: /data
      - type: bind
        source: ./.data/neo4j/logs
        target: /logs
      - type: bind
        source: ./.data/neo4j/import
        target: /import
    healthcheck:
      test: ["CMD-SHELL", "/var/lib/neo4j/bin/neo4j-admin server status >/dev/null 2>&1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  qdrant:
    image: qdrant/qdrant:v1.15.4
    container_name: qdrant-graphrag
    restart: unless-stopped
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__CLUSTER__ENABLED: "false"
    ports:
      - "${QDRANT_HTTP_PORT:-6333}:6333"
      - "${QDRANT_GRPC_PORT:-6334}:6334"
    healthcheck:
      test:
        - CMD-SHELL
        - >
          bash -ec '
            exec 3<>/dev/tcp/127.0.0.1/6333 &&
            printf "GET /readyz HTTP/1.0\r\n\r\n" >&3 &&
            read -r status_line <&3 &&
            case "$${status_line}" in
              *"200"*) exit 0 ;;
              *) exit 1 ;;
            esac
          '
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - type: bind
        source: ./.data/qdrant/storage
        target: /qdrant/storage

  smoke-tests:
    image: python:3.12-slim
    depends_on:
      neo4j:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    environment:
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: "stubs:src"
      NEO4J_HOST: neo4j
      NEO4J_URI: "bolt://neo4j:7687"
      NEO4J_HTTP_HOST: neo4j
      NEO4J_HTTP_PORT: "7474"
      NEO4J_BOLT_PORT: "7687"
      NEO4J_BOLT_ADVERTISED_ADDRESS: "neo4j:7687"
      NEO4J_HTTP_ADVERTISED_ADDRESS: "neo4j:7474"
      NEO4J_USERNAME: "${NEO4J_USERNAME:-neo4j}"
      NEO4J_PASSWORD: "${NEO4J_PASSWORD:-neo4j}"
      QDRANT_HOST: qdrant
      QDRANT_URL: "http://qdrant:6333"
      QDRANT_HTTP_PORT: "6333"
      QDRANT_GRPC_PORT: "6334"
    volumes:
      - .:/workspace
    working_dir: /workspace
    entrypoint: ""
    profiles:
      - tests

networks:
  default:
    name: graphrag-local
