blank_issues_enabled: false
contact_links:
  - name: Neo4j GraphRAG Support Discussions
    url: https://github.com/DrJLabs/FancyRAG/discussions
    about: Ask questions, share ideas, or get help from the community.
